import unittest

from manga_checker.volume import is_volume_one


class VolumeOneTests(unittest.TestCase):
    def test_volume_field(self) -> None:
        self.assertTrue(is_volume_one("リベンジアクト", "1"))
        self.assertTrue(is_volume_one("リベンジアクト", "01"))
        self.assertTrue(is_volume_one("リベンジアクト", "０１"))
        self.assertTrue(is_volume_one("リベンジアクト", "第1巻"))
        self.assertTrue(is_volume_one("リベンジアクト", "１巻"))
        self.assertFalse(is_volume_one("リベンジアクト", "2"))
        self.assertFalse(is_volume_one("蒼き鋼のアルペジオ", "31"))

    def test_title_patterns(self) -> None:
        self.assertTrue(is_volume_one("夜は猫といっしょ(1)"))
        self.assertTrue(is_volume_one("夜は猫といっしょ（１）"))
        self.assertTrue(is_volume_one("魔入りました!入間くん 僕同盟のゲーム道(1)"))
        self.assertTrue(is_volume_one("はじめての冒険 第1巻"))
        self.assertTrue(is_volume_one("はじめての冒険 1巻"))
        self.assertTrue(is_volume_one("Example Vol.1"))
        self.assertTrue(is_volume_one("夜は猫といっしょ 1"))
        self.assertTrue(is_volume_one("夜は猫といっしょ １"))
        self.assertTrue(is_volume_one("夜は猫といっしょ 1 特装版"))
        self.assertTrue(is_volume_one("あっ、悪魔ちゃん 1"))
        self.assertTrue(is_volume_one("ヒトナー 1"))
        self.assertTrue(is_volume_one("ヒトナー １"))
        self.assertTrue(is_volume_one("あっ、悪魔ちゃん　1"))
        self.assertTrue(is_volume_one("ヒトナー　１"))
        self.assertTrue(is_volume_one("ヒトナー 1　続刊"))
        self.assertTrue(is_volume_one("ヒトナー　1 続刊"))
        self.assertTrue(is_volume_one("作品 1:特装版"))
        self.assertTrue(is_volume_one("夜は猫といっしょ(01)"))
        self.assertTrue(is_volume_one("夜は猫といっしょ（０１）"))
        self.assertTrue(is_volume_one("夜は猫といっしょ 01"))
        self.assertTrue(is_volume_one("夜は猫といっしょ ０１"))
        self.assertTrue(is_volume_one("はじめての冒険 第01巻"))
        self.assertTrue(is_volume_one("はじめての冒険 01巻"))
        self.assertTrue(is_volume_one("はじめての冒険 ０１巻"))
        self.assertTrue(is_volume_one("Example Vol.01"))
        self.assertFalse(is_volume_one("To Loveる 短編集 Parade"))
        self.assertTrue(is_volume_one("ルノリータ 第1巻"))
        self.assertFalse(is_volume_one("死神と令嬢"))
        self.assertFalse(is_volume_one("公式ファンブック"))
        self.assertFalse(is_volume_one("作品名 上巻"))
        self.assertFalse(is_volume_one("作品名 前編"))
        self.assertFalse(is_volume_one("傑作選"))
        self.assertFalse(is_volume_one("アンソロジー"))
        self.assertTrue(is_volume_one("アンソロジーコミック 1"))
        self.assertTrue(is_volume_one("アンソロジーコミック第1巻"))
        self.assertFalse(is_volume_one("作品名 下巻"))
        self.assertFalse(is_volume_one("作品名 後編"))
        self.assertFalse(is_volume_one("作品名 中巻"))
        self.assertFalse(is_volume_one("夜は猫といっしょ(10)"))
        self.assertFalse(is_volume_one("進撃の巨人(11)"))
        self.assertFalse(is_volume_one("進撃の巨人 11巻"))
        self.assertFalse(is_volume_one("進撃の巨人 21巻"))
        self.assertFalse(is_volume_one("1日10分でわかる世界史"))
        self.assertFalse(is_volume_one("あおのたつき", "20"))
        self.assertFalse(is_volume_one("TYPE-1 ガイド"))
        self.assertFalse(is_volume_one("The 1st Battle"))
        self.assertFalse(is_volume_one("進撃の巨人 10巻"))
        self.assertFalse(is_volume_one("進撃の巨人 12巻"))


if __name__ == "__main__":
    unittest.main()
